// This file was auto-generated by ML.NET Model Builder. 

using System;
using GameLibraryML.Model;

namespace GameLibraryML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Username = @"Ionut",
                Gamename = @"CSGo",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");
            Console.WriteLine($"Username: {sampleData.Username}");
            Console.WriteLine($"Gamename: {sampleData.Gamename}");
            Console.WriteLine($"\n\nPredicted Rating value {predictionResult.Prediction} \nPredicted Rating scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
