// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace GameLibraryML.Model
{
    public class ModelInput
    {
        [ColumnName("username"), LoadColumn(0)]
        public string Username { get; set; }


        [ColumnName("gamename"), LoadColumn(1)]
        public string Gamename { get; set; }


        [ColumnName("rating"), LoadColumn(2)]
        public string Rating { get; set; }


    }
}
